### ISSUE TITLE
CodeQL action failing

### ISSUE THREAD

**Issue by ryangray** [chris-y/zmakebas#11]
I got a notice on my fork that the CodeQL scanning workflow failed, and it says it's due to v1 being deprecated in favor of v2 ([see here](https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/)). It says it was triggered by me pushing commit de323cb, but that seems to be your mod, and it looks to have happened when I synced my fork after you merged my pull request. I did look in `.github/workflows/codeql-analysis.yml`, and I did see references to `@v1` for `github/codeql-action`, so I guess those need changing to `@v2`.

**Comment by chris-y** [comment]
I've updated it, but mine was disabled automatically some months ago and I'm not entirely sure how to re-enable it (I only get an option to disable, so I've disabled and re-enabled to see if that will do it)

**Comment by ryangray** [comment]
I updated, but it still failed. Looking more closely, it seems there are two remaining warnings:

1. A warning to remove the step "git checkout HEAD^2". See [here](https://docs.github.com/en/code-security/code-scanning/troubleshooting-code-scanning/unnecessary-step-found)
2. The following action uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

However, it seems the real problem is that there is still an error that looks to do with permissions it runs with, which are a read-only:

    GITHUB_TOKEN Permissions
      Contents: read
      Metadata: read
      Packages: read

This may have to do with [dependabot and permissions](https://github.blog/changelog/2021-10-06-github-actions-workflows-triggered-by-dependabot-prs-will-respect-permissions-key-in-workflows/).

For now, I guess I can disable this workflow.

**Comment by chris-y** [comment]
I've fixed those warnings in theory. The permissions might be because it's a fork? Still haven't figured out how to re-enable it here!
